<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/09/24 21:01:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=letechde_qdpm79;host=localhost',
  'profiler' => false,
  'username' => 'letechde_qdpm79',
  'password' => '%29m-%5DS347.7pYo1s%5B',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
