<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 04:14:25
sfConfig::add(array(
  'mod_tasksgroups_enabled' => true,
  'mod_tasksgroups_view_class' => 'sfPHP',
));
