<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 04:12:52
sfConfig::add(array(
  'mod_attachments_enabled' => true,
  'mod_attachments_view_class' => 'sfPHP',
));
