<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 04:16:10
sfConfig::add(array(
  'mod_taskscomments_enabled' => true,
  'mod_taskscomments_view_class' => 'sfPHP',
));
