<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/24 15:01:02
sfConfig::add(array(
  'mod_pagenotfound_enabled' => true,
  'mod_pagenotfound_view_class' => 'sfPHP',
));
