<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 10:23:41
sfConfig::add(array(
  'mod_ticketsreports_enabled' => true,
  'mod_ticketsreports_view_class' => 'sfPHP',
));
