<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 10:30:17
sfConfig::add(array(
  'mod_tasksstatus_enabled' => true,
  'mod_tasksstatus_view_class' => 'sfPHP',
));
