<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 04:19:48
sfConfig::add(array(
  'mod_configuration_enabled' => true,
  'mod_configuration_view_class' => 'sfPHP',
));
