<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 10:22:02
sfConfig::add(array(
  'mod_usersgroups_enabled' => true,
  'mod_usersgroups_view_class' => 'sfPHP',
));
