<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 10:22:09
sfConfig::add(array(
  'mod_projectsstatus_enabled' => true,
  'mod_projectsstatus_view_class' => 'sfPHP',
));
