<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 10:23:43
sfConfig::add(array(
  'mod_userreports_enabled' => true,
  'mod_userreports_view_class' => 'sfPHP',
));
