<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 10:31:17
sfConfig::add(array(
  'mod_discussions_enabled' => true,
  'mod_discussions_view_class' => 'sfPHP',
));
