<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 04:13:52
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
