<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 04:16:50
sfConfig::add(array(
  'mod_projectsreports_enabled' => true,
  'mod_projectsreports_view_class' => 'sfPHP',
));
