<?php
// auto-generated by sfSecurityConfigHandler
// date: 2018/09/25 10:23:38
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'reports_access_gantt',
  ),
);
