<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/09/25 10:22:14
sfConfig::add(array(
  'mod_departments_enabled' => true,
  'mod_departments_view_class' => 'sfPHP',
));
