  
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:dbname=letechde_qdpm79;host=localhost'
      profiler: false
      username: letechde_qdpm79
      password: "<?php echo urlencode(')m-]S347.7pYo1s[') ; ?>"
      attributes:
        quote_identifier: true  
  